export const DEFAULT_THEME = {
    NAV_BAR_TITLE_COLOR : 'white',
    NAV_BAR_BG_COLOR : '#181818',
    BODY_BG_COLOR : '#ECEEF1',
    BODY_ICON_COLOR : '#181818',
    MODAL_CARD_HEADER_COLOR: '#262626',
    MODAL_CARD_BODY_COLOR: '#F5F5F5',
    MODAL_CARD_FOOTER_COLOR:'#262626',
    MODAL_CARD_ICON_COLOR: '#F5F5F5'
}